export type CityInfo = {
  key: string
  name: string
  country: string
  countryCode: string
  latitude: number
  longitude: number
}

export const CITIES: CityInfo[] = [
  {
    key: 'abha-sa',
    name: 'Abha',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 18.2164,
    longitude: 42.5053,
  },
  {
    key: 'abidjan-ci',
    name: 'Abidjan',
    country: 'Ivory Coast',
    countryCode: 'CI',
    latitude: 5.36,
    longitude: -4.0083,
  },
  {
    key: 'abu-dhabi-ae',
    name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 24.4539,
    longitude: 54.3773,
  },
  {
    key: 'abuja-ng',
    name: 'Abuja',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 9.0579,
    longitude: 7.4951,
  },
  {
    key: 'accra-gh',
    name: 'Accra',
    country: 'Ghana',
    countryCode: 'GH',
    latitude: 5.6037,
    longitude: -0.187,
  },
  {
    key: 'adana-tr',
    name: 'Adana',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 37,
    longitude: 35.3213,
  },
  {
    key: 'addis-ababa-et',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    latitude: 9.025,
    longitude: 38.7469,
  },
  {
    key: 'agadir-ma',
    name: 'Agadir',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 30.4278,
    longitude: -9.5981,
  },
  {
    key: 'ahmedabad-in',
    name: 'Ahmedabad',
    country: 'India',
    countryCode: 'IN',
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    key: 'ajman-ae',
    name: 'Ajman',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.4052,
    longitude: 55.5136,
  },
  {
    key: 'al-ain-ae',
    name: 'Al Ain',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 24.1917,
    longitude: 55.7606,
  },
  {
    key: 'alexandria-eg',
    name: 'Alexandria',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 31.2001,
    longitude: 29.9187,
  },
  {
    key: 'algiers-dz',
    name: 'Algiers',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 36.7538,
    longitude: 3.0588,
  },
  {
    key: 'almaty-kz',
    name: 'Almaty',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    latitude: 43.222,
    longitude: 76.8512,
  },
  {
    key: 'amman-jo',
    name: 'Amman',
    country: 'Jordan',
    countryCode: 'JO',
    latitude: 31.9454,
    longitude: 35.9284,
  },
  {
    key: 'amsterdam-nl',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    key: 'ankara-tr',
    name: 'Ankara',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 39.9334,
    longitude: 32.8597,
  },
  {
    key: 'antalya-tr',
    name: 'Antalya',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 36.8969,
    longitude: 30.7133,
  },
  {
    key: 'antananarivo-mg',
    name: 'Antananarivo',
    country: 'Madagascar',
    countryCode: 'MG',
    latitude: -18.8792,
    longitude: 47.5079,
  },
  {
    key: 'ashgabat-tm',
    name: 'Ashgabat',
    country: 'Turkmenistan',
    countryCode: 'TM',
    latitude: 37.9601,
    longitude: 58.3261,
  },
  {
    key: 'astana-kz',
    name: 'Astana',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    latitude: 51.1694,
    longitude: 71.4491,
  },
  {
    key: 'aswan-eg',
    name: 'Aswan',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 24.0889,
    longitude: 32.8998,
  },
  {
    key: 'athens-gr',
    name: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    latitude: 37.9838,
    longitude: 23.7275,
  },
  {
    key: 'atlanta-us',
    name: 'Atlanta',
    country: 'United States',
    countryCode: 'US',
    latitude: 33.749,
    longitude: -84.388,
  },
  {
    key: 'auckland-nz',
    name: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    latitude: -36.8485,
    longitude: 174.7633,
  },
  {
    key: 'baghdad-iq',
    name: 'Baghdad',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 33.3128,
    longitude: 44.3615,
  },
  {
    key: 'baku-az',
    name: 'Baku',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    latitude: 40.4093,
    longitude: 49.8671,
  },
  {
    key: 'bamako-ml',
    name: 'Bamako',
    country: 'Mali',
    countryCode: 'ML',
    latitude: 12.6392,
    longitude: -8.0029,
  },
  {
    key: 'bandar-seri-begawan-bn',
    name: 'Bandar Seri Begawan',
    country: 'Brunei',
    countryCode: 'BN',
    latitude: 4.9031,
    longitude: 114.9398,
  },
  {
    key: 'bandung-id',
    name: 'Bandung',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.9175,
    longitude: 107.6191,
  },
  {
    key: 'bangalore-in',
    name: 'Bangalore',
    country: 'India',
    countryCode: 'IN',
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    key: 'bangkok-th',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    key: 'barcelona-es',
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 41.3874,
    longitude: 2.1686,
  },
  {
    key: 'basra-iq',
    name: 'Basra',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 30.5085,
    longitude: 47.7804,
  },
  {
    key: 'beirut-lb',
    name: 'Beirut',
    country: 'Lebanon',
    countryCode: 'LB',
    latitude: 33.8938,
    longitude: 35.5018,
  },
  {
    key: 'benghazi-ly',
    name: 'Benghazi',
    country: 'Libya',
    countryCode: 'LY',
    latitude: 32.1194,
    longitude: 20.0868,
  },
  {
    key: 'beni-mellal-ma',
    name: 'Beni Mellal',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 32.3373,
    longitude: -6.3498,
  },
  {
    key: 'berlin-de',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 52.52,
    longitude: 13.405,
  },
  {
    key: 'birmingham-gb',
    name: 'Birmingham',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 52.4862,
    longitude: -1.8904,
  },
  {
    key: 'bishkek-kg',
    name: 'Bishkek',
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    latitude: 42.8746,
    longitude: 74.5698,
  },
  {
    key: 'bogota-co',
    name: 'Bogota',
    country: 'Colombia',
    countryCode: 'CO',
    latitude: 4.711,
    longitude: -74.0721,
  },
  {
    key: 'brussels-be',
    name: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    latitude: 50.8503,
    longitude: 4.3517,
  },
  {
    key: 'bucharest-ro',
    name: 'Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    latitude: 44.4268,
    longitude: 26.1025,
  },
  {
    key: 'buenos-aires-ar',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    latitude: -34.6037,
    longitude: -58.3816,
  },
  {
    key: 'bursa-tr',
    name: 'Bursa',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 40.1885,
    longitude: 29.061,
  },
  {
    key: 'cairo-eg',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    key: 'cape-town-za',
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -33.9249,
    longitude: 18.4241,
  },
  {
    key: 'casablanca-ma',
    name: 'Casablanca',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 33.5731,
    longitude: -7.5898,
  },
  {
    key: 'chattogram-bd',
    name: 'Chattogram',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 22.3569,
    longitude: 91.7832,
  },
  {
    key: 'chennai-in',
    name: 'Chennai',
    country: 'India',
    countryCode: 'IN',
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    key: 'chicago-us',
    name: 'Chicago',
    country: 'United States',
    countryCode: 'US',
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    key: 'colombo-lk',
    name: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    latitude: 6.9271,
    longitude: 79.8612,
  },
  {
    key: 'conakry-gn',
    name: 'Conakry',
    country: 'Guinea',
    countryCode: 'GN',
    latitude: 9.6412,
    longitude: -13.5784,
  },
  {
    key: 'constantine-dz',
    name: 'Constantine',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 36.365,
    longitude: 6.6147,
  },
  {
    key: 'copenhagen-dk',
    name: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    latitude: 55.6761,
    longitude: 12.5683,
  },
  {
    key: 'dakar-sn',
    name: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    latitude: 14.7167,
    longitude: -17.4677,
  },
  {
    key: 'dallas-us',
    name: 'Dallas',
    country: 'United States',
    countryCode: 'US',
    latitude: 32.7767,
    longitude: -96.797,
  },
  {
    key: 'damascus-sy',
    name: 'Damascus',
    country: 'Syria',
    countryCode: 'SY',
    latitude: 33.5138,
    longitude: 36.2765,
  },
  {
    key: 'dammam-sa',
    name: 'Dammam',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 26.3927,
    longitude: 49.9777,
  },
  {
    key: 'dar-es-salaam-tz',
    name: 'Dar es Salaam',
    country: 'Tanzania',
    countryCode: 'TZ',
    latitude: -6.7924,
    longitude: 39.2083,
  },
  {
    key: 'delhi-in',
    name: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.7041,
    longitude: 77.1025,
  },
  {
    key: 'detroit-us',
    name: 'Detroit',
    country: 'United States',
    countryCode: 'US',
    latitude: 42.3314,
    longitude: -83.0458,
  },
  {
    key: 'dhaka-bd',
    name: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 23.8103,
    longitude: 90.4125,
  },
  {
    key: 'diyarbakir-tr',
    name: 'Diyarbakir',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 37.9144,
    longitude: 40.2306,
  },
  {
    key: 'djibouti-dj',
    name: 'Djibouti',
    country: 'Djibouti',
    countryCode: 'DJ',
    latitude: 11.5721,
    longitude: 43.1456,
  },
  {
    key: 'doha-qa',
    name: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    latitude: 25.2854,
    longitude: 51.531,
  },
  {
    key: 'douala-cm',
    name: 'Douala',
    country: 'Cameroon',
    countryCode: 'CM',
    latitude: 4.0511,
    longitude: 9.7679,
  },
  {
    key: 'dubai-ae',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.2048,
    longitude: 55.2708,
  },
  {
    key: 'dublin-ie',
    name: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    latitude: 53.3498,
    longitude: -6.2603,
  },
  {
    key: 'durban-za',
    name: 'Durban',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -29.8587,
    longitude: 31.0218,
  },
  {
    key: 'dushanbe-tj',
    name: 'Dushanbe',
    country: 'Tajikistan',
    countryCode: 'TJ',
    latitude: 38.5598,
    longitude: 68.774,
  },
  {
    key: 'erbil-iq',
    name: 'Erbil',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 36.1912,
    longitude: 44.0119,
  },
  {
    key: 'faisalabad-pk',
    name: 'Faisalabad',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 31.4187,
    longitude: 73.0791,
  },
  {
    key: 'fez-ma',
    name: 'Fez',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.0181,
    longitude: -5.0078,
  },
  {
    key: 'frankfurt-de',
    name: 'Frankfurt',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 50.1109,
    longitude: 8.6821,
  },
  {
    key: 'freetown-sl',
    name: 'Freetown',
    country: 'Sierra Leone',
    countryCode: 'SL',
    latitude: 8.4657,
    longitude: -13.2317,
  },
  {
    key: 'gaza-ps',
    name: 'Gaza',
    country: 'Palestine',
    countryCode: 'PS',
    latitude: 31.5017,
    longitude: 34.4668,
  },
  {
    key: 'gaziantep-tr',
    name: 'Gaziantep',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 37.0662,
    longitude: 37.3833,
  },
  {
    key: 'grozny-ru',
    name: 'Grozny',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 43.3181,
    longitude: 45.6947,
  },
  {
    key: 'hamburg-de',
    name: 'Hamburg',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 53.5511,
    longitude: 9.9937,
  },
  {
    key: 'harare-zw',
    name: 'Harare',
    country: 'Zimbabwe',
    countryCode: 'ZW',
    latitude: -17.8252,
    longitude: 31.0335,
  },
  {
    key: 'helsinki-fi',
    name: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    latitude: 60.1699,
    longitude: 24.9384,
  },
  {
    key: 'houston-us',
    name: 'Houston',
    country: 'United States',
    countryCode: 'US',
    latitude: 29.7604,
    longitude: -95.3698,
  },
  {
    key: 'hyderabad-in',
    name: 'Hyderabad',
    country: 'India',
    countryCode: 'IN',
    latitude: 17.385,
    longitude: 78.4867,
  },
  {
    key: 'isfahan-ir',
    name: 'Isfahan',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 32.6546,
    longitude: 51.668,
  },
  {
    key: 'islamabad-pk',
    name: 'Islamabad',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 33.6844,
    longitude: 73.0479,
  },
  {
    key: 'istanbul-tr',
    name: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    key: 'izmir-tr',
    name: 'Izmir',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 38.4237,
    longitude: 27.1428,
  },
  {
    key: 'jaipur-in',
    name: 'Jaipur',
    country: 'India',
    countryCode: 'IN',
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    key: 'jakarta-id',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.2088,
    longitude: 106.8456,
  },
  {
    key: 'jeddah-sa',
    name: 'Jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.4858,
    longitude: 39.1925,
  },
  {
    key: 'jerusalem-ps',
    name: 'Jerusalem',
    country: 'Palestine',
    countryCode: 'PS',
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    key: 'johannesburg-za',
    name: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -26.2041,
    longitude: 28.0473,
  },
  {
    key: 'kabul-af',
    name: 'Kabul',
    country: 'Afghanistan',
    countryCode: 'AF',
    latitude: 34.5553,
    longitude: 69.2075,
  },
  {
    key: 'kampala-ug',
    name: 'Kampala',
    country: 'Uganda',
    countryCode: 'UG',
    latitude: 0.3476,
    longitude: 32.5825,
  },
  {
    key: 'kano-ng',
    name: 'Kano',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 12.0022,
    longitude: 8.592,
  },
  {
    key: 'karachi-pk',
    name: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 24.8607,
    longitude: 67.0011,
  },
  {
    key: 'kayseri-tr',
    name: 'Kayseri',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 38.7312,
    longitude: 35.4787,
  },
  {
    key: 'kenitra-ma',
    name: 'Kenitra',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.261,
    longitude: -6.5802,
  },
  {
    key: 'khartoum-sd',
    name: 'Khartoum',
    country: 'Sudan',
    countryCode: 'SD',
    latitude: 15.5007,
    longitude: 32.5599,
  },
  {
    key: 'kigali-rw',
    name: 'Kigali',
    country: 'Rwanda',
    countryCode: 'RW',
    latitude: -1.9403,
    longitude: 29.8739,
  },
  {
    key: 'kolkata-in',
    name: 'Kolkata',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    key: 'konya-tr',
    name: 'Konya',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 37.8746,
    longitude: 32.4932,
  },
  {
    key: 'kuala-lumpur-my',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 3.139,
    longitude: 101.6869,
  },
  {
    key: 'kuwait-city-kw',
    name: 'Kuwait City',
    country: 'Kuwait',
    countryCode: 'KW',
    latitude: 29.3759,
    longitude: 47.9774,
  },
  {
    key: 'lagos-ng',
    name: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.5244,
    longitude: 3.3792,
  },
  {
    key: 'lahore-pk',
    name: 'Lahore',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 31.5204,
    longitude: 74.3587,
  },
  {
    key: 'lima-pe',
    name: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    key: 'lisbon-pt',
    name: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    latitude: 38.7223,
    longitude: -9.1393,
  },
  {
    key: 'lome-tg',
    name: 'Lome',
    country: 'Togo',
    countryCode: 'TG',
    latitude: 6.1725,
    longitude: 1.2314,
  },
  {
    key: 'london-gb',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    key: 'los-angeles-us',
    name: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    key: 'lucknow-in',
    name: 'Lucknow',
    country: 'India',
    countryCode: 'IN',
    latitude: 26.8467,
    longitude: 80.9462,
  },
  {
    key: 'lusaka-zm',
    name: 'Lusaka',
    country: 'Zambia',
    countryCode: 'ZM',
    latitude: -15.3875,
    longitude: 28.3228,
  },
  {
    key: 'luxor-eg',
    name: 'Luxor',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 25.6872,
    longitude: 32.6396,
  },
  {
    key: 'lyon-fr',
    name: 'Lyon',
    country: 'France',
    countryCode: 'FR',
    latitude: 45.764,
    longitude: 4.8357,
  },
  {
    key: 'madrid-es',
    name: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    key: 'makassar-id',
    name: 'Makassar',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -5.1477,
    longitude: 119.4327,
  },
  {
    key: 'makkah-sa',
    name: 'Makkah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.3891,
    longitude: 39.8579,
  },
  {
    key: 'malacca-my',
    name: 'Malacca',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 2.1896,
    longitude: 102.2501,
  },
  {
    key: 'male-mv',
    name: 'Male',
    country: 'Maldives',
    countryCode: 'MV',
    latitude: 4.1755,
    longitude: 73.5093,
  },
  {
    key: 'manama-bh',
    name: 'Manama',
    country: 'Bahrain',
    countryCode: 'BH',
    latitude: 26.2285,
    longitude: 50.586,
  },
  {
    key: 'manchester-gb',
    name: 'Manchester',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    key: 'manila-ph',
    name: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.5995,
    longitude: 120.9842,
  },
  {
    key: 'maputo-mz',
    name: 'Maputo',
    country: 'Mozambique',
    countryCode: 'MZ',
    latitude: -25.9692,
    longitude: 32.5732,
  },
  {
    key: 'marrakech-ma',
    name: 'Marrakech',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 31.6295,
    longitude: -7.9811,
  },
  {
    key: 'marseille-fr',
    name: 'Marseille',
    country: 'France',
    countryCode: 'FR',
    latitude: 43.2965,
    longitude: 5.3698,
  },
  {
    key: 'mazar-i-sharif-af',
    name: 'Mazar-i-Sharif',
    country: 'Afghanistan',
    countryCode: 'AF',
    latitude: 36.7069,
    longitude: 67.11,
  },
  {
    key: 'medan-id',
    name: 'Medan',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: 3.5952,
    longitude: 98.6722,
  },
  {
    key: 'medina-sa',
    name: 'Medina',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.5247,
    longitude: 39.5692,
  },
  {
    key: 'meknes-ma',
    name: 'Meknes',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 33.8935,
    longitude: -5.5547,
  },
  {
    key: 'melbourne-au',
    name: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -37.8136,
    longitude: 144.9631,
  },
  {
    key: 'mexico-city-mx',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.4326,
    longitude: -99.1332,
  },
  {
    key: 'milan-it',
    name: 'Milan',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.4642,
    longitude: 9.19,
  },
  {
    key: 'minneapolis-us',
    name: 'Minneapolis',
    country: 'United States',
    countryCode: 'US',
    latitude: 44.9778,
    longitude: -93.265,
  },
  {
    key: 'mogadishu-so',
    name: 'Mogadishu',
    country: 'Somalia',
    countryCode: 'SO',
    latitude: 2.0469,
    longitude: 45.3182,
  },
  {
    key: 'montreal-ca',
    name: 'Montreal',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 45.5017,
    longitude: -73.5673,
  },
  {
    key: 'moscow-ru',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 55.7558,
    longitude: 37.6173,
  },
  {
    key: 'mosul-iq',
    name: 'Mosul',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 36.335,
    longitude: 43.1189,
  },
  {
    key: 'multan-pk',
    name: 'Multan',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 30.1575,
    longitude: 71.5249,
  },
  {
    key: 'mumbai-in',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    key: 'munich-de',
    name: 'Munich',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 48.1351,
    longitude: 11.582,
  },
  {
    key: 'muscat-om',
    name: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    latitude: 23.588,
    longitude: 58.3829,
  },
  {
    key: 'nador-ma',
    name: 'Nador',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 35.1681,
    longitude: -2.933,
  },
  {
    key: 'nairobi-ke',
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    latitude: -1.2921,
    longitude: 36.8219,
  },
  {
    key: 'new-york-us',
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    key: 'niamey-ne',
    name: 'Niamey',
    country: 'Niger',
    countryCode: 'NE',
    latitude: 13.5116,
    longitude: 2.1254,
  },
  {
    key: 'nouakchott-mr',
    name: 'Nouakchott',
    country: 'Mauritania',
    countryCode: 'MR',
    latitude: 18.0735,
    longitude: -15.9582,
  },
  {
    key: 'oran-dz',
    name: 'Oran',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 35.6969,
    longitude: -0.6331,
  },
  {
    key: 'oslo-no',
    name: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    latitude: 59.9139,
    longitude: 10.7522,
  },
  {
    key: 'ottawa-ca',
    name: 'Ottawa',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 45.4215,
    longitude: -75.6972,
  },
  {
    key: 'ouagadougou-bf',
    name: 'Ouagadougou',
    country: 'Burkina Faso',
    countryCode: 'BF',
    latitude: 12.3714,
    longitude: -1.5197,
  },
  {
    key: 'oujda-ma',
    name: 'Oujda',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.6814,
    longitude: -1.9086,
  },
  {
    key: 'palembang-id',
    name: 'Palembang',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -2.9761,
    longitude: 104.7754,
  },
  {
    key: 'paris-fr',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    key: 'penang-my',
    name: 'Penang',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 5.4164,
    longitude: 100.3327,
  },
  {
    key: 'peshawar-pk',
    name: 'Peshawar',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 34.0151,
    longitude: 71.5249,
  },
  {
    key: 'philadelphia-us',
    name: 'Philadelphia',
    country: 'United States',
    countryCode: 'US',
    latitude: 39.9526,
    longitude: -75.1652,
  },
  {
    key: 'port-moresby-pg',
    name: 'Port Moresby',
    country: 'Papua New Guinea',
    countryCode: 'PG',
    latitude: -9.4438,
    longitude: 147.1803,
  },
  {
    key: 'prague-cz',
    name: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    latitude: 50.0755,
    longitude: 14.4378,
  },
  {
    key: 'pune-in',
    name: 'Pune',
    country: 'India',
    countryCode: 'IN',
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    key: 'putrajaya-my',
    name: 'Putrajaya',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 2.9264,
    longitude: 101.6964,
  },
  {
    key: 'quetta-pk',
    name: 'Quetta',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 30.1798,
    longitude: 66.975,
  },
  {
    key: 'rabat-ma',
    name: 'Rabat',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.0209,
    longitude: -6.8416,
  },
  {
    key: 'rawalpindi-pk',
    name: 'Rawalpindi',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 33.5651,
    longitude: 73.0169,
  },
  {
    key: 'riyadh-sa',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.7136,
    longitude: 46.6753,
  },
  {
    key: 'rome-it',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    key: 'rotterdam-nl',
    name: 'Rotterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    latitude: 51.9244,
    longitude: 4.4777,
  },
  {
    key: 'safi-ma',
    name: 'Safi',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 32.2994,
    longitude: -9.2372,
  },
  {
    key: 'salalah-om',
    name: 'Salalah',
    country: 'Oman',
    countryCode: 'OM',
    latitude: 17.0151,
    longitude: 54.0924,
  },
  {
    key: 'samarkand-uz',
    name: 'Samarkand',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    latitude: 39.6542,
    longitude: 66.9597,
  },
  {
    key: 'samsun-tr',
    name: 'Samsun',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 41.2867,
    longitude: 36.33,
  },
  {
    key: 'san-francisco-us',
    name: 'San Francisco',
    country: 'United States',
    countryCode: 'US',
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    key: 'sanaa-ye',
    name: 'Sanaa',
    country: 'Yemen',
    countryCode: 'YE',
    latitude: 15.3694,
    longitude: 44.191,
  },
  {
    key: 'sao-paulo-br',
    name: 'Sao Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -23.5505,
    longitude: -46.6333,
  },
  {
    key: 'sarajevo-ba',
    name: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    latitude: 43.8563,
    longitude: 18.4131,
  },
  {
    key: 'semarang-id',
    name: 'Semarang',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.9666,
    longitude: 110.4196,
  },
  {
    key: 'seoul-kr',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 37.5665,
    longitude: 126.978,
  },
  {
    key: 'setif-dz',
    name: 'Setif',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 36.1898,
    longitude: 5.4108,
  },
  {
    key: 'sfax-tn',
    name: 'Sfax',
    country: 'Tunisia',
    countryCode: 'TN',
    latitude: 34.7406,
    longitude: 10.7603,
  },
  {
    key: 'sharjah-ae',
    name: 'Sharjah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.3463,
    longitude: 55.4209,
  },
  {
    key: 'singapore-sg',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    key: 'sofia-bg',
    name: 'Sofia',
    country: 'Bulgaria',
    countryCode: 'BG',
    latitude: 42.6977,
    longitude: 23.3219,
  },
  {
    key: 'stockholm-se',
    name: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    key: 'surabaya-id',
    name: 'Surabaya',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -7.2575,
    longitude: 112.7521,
  },
  {
    key: 'sydney-au',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    key: 'sylhet-bd',
    name: 'Sylhet',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 24.8949,
    longitude: 91.8687,
  },
  {
    key: 'tabriz-ir',
    name: 'Tabriz',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 38.08,
    longitude: 46.2919,
  },
  {
    key: 'tabuk-sa',
    name: 'Tabuk',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 28.3838,
    longitude: 36.555,
  },
  {
    key: 'taif-sa',
    name: 'Taif',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.2703,
    longitude: 40.4158,
  },
  {
    key: 'tangier-ma',
    name: 'Tangier',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 35.7595,
    longitude: -5.834,
  },
  {
    key: 'tashkent-uz',
    name: 'Tashkent',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    latitude: 41.2995,
    longitude: 69.2401,
  },
  {
    key: 'tehran-ir',
    name: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 35.6892,
    longitude: 51.389,
  },
  {
    key: 'tetouan-ma',
    name: 'Tetouan',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 35.5889,
    longitude: -5.3626,
  },
  {
    key: 'tirana-al',
    name: 'Tirana',
    country: 'Albania',
    countryCode: 'AL',
    latitude: 41.3275,
    longitude: 19.8187,
  },
  {
    key: 'tlemcen-dz',
    name: 'Tlemcen',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 34.8828,
    longitude: -1.3167,
  },
  {
    key: 'tokyo-jp',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    key: 'toronto-ca',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 43.6532,
    longitude: -79.3832,
  },
  {
    key: 'tripoli-lb',
    name: 'Tripoli',
    country: 'Lebanon',
    countryCode: 'LB',
    latitude: 34.4367,
    longitude: 35.8497,
  },
  {
    key: 'tripoli-ly',
    name: 'Tripoli',
    country: 'Libya',
    countryCode: 'LY',
    latitude: 32.8872,
    longitude: 13.1913,
  },
  {
    key: 'tunis-tn',
    name: 'Tunis',
    country: 'Tunisia',
    countryCode: 'TN',
    latitude: 36.8065,
    longitude: 10.1815,
  },
  {
    key: 'vancouver-ca',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 49.2827,
    longitude: -123.1207,
  },
  {
    key: 'vienna-at',
    name: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    latitude: 48.2082,
    longitude: 16.3738,
  },
  {
    key: 'warsaw-pl',
    name: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    latitude: 52.2297,
    longitude: 21.0122,
  },
  {
    key: 'washington-dc-us',
    name: 'Washington DC',
    country: 'United States',
    countryCode: 'US',
    latitude: 38.9072,
    longitude: -77.0369,
  },
  {
    key: 'yogyakarta-id',
    name: 'Yogyakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -7.7956,
    longitude: 110.3695,
  },
  {
    key: 'zagreb-hr',
    name: 'Zagreb',
    country: 'Croatia',
    countryCode: 'HR',
    latitude: 45.815,
    longitude: 15.9819,
  },
  {
    key: 'zanzibar-tz',
    name: 'Zanzibar',
    country: 'Tanzania',
    countryCode: 'TZ',
    latitude: -6.1659,
    longitude: 39.1989,
  },
  {
    key: 'zurich-ch',
    name: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    latitude: 47.3769,
    longitude: 8.5417,
  },
]
